"""Native AI substrate."""

from sibyl_core.ai.errors import (
    AIError,
    LLMConfigError,
    LLMError,
    LLMProviderError,
    LLMRateLimitError,
    LLMTimeoutError,
    LLMValidationError,
    classify_llm_exception,
)
from sibyl_core.ai.llm import (
    ConfigField,
    EnvConfigSource,
    Extractor,
    Generator,
    LLMConfig,
    LLMConfigSource,
    LLMSurface,
    ResolvedLLMConfig,
    get_config_source,
    invalidate_llm_config,
    resolve_llm_config,
    set_config_source,
)
from sibyl_core.ai.providers import build_model, resolve_provider_model_id
from sibyl_core.ai.registry import (
    ModelCapability,
    ModelEntry,
    ModelKind,
    ModelRegistry,
    embedding_entries,
    llm_entries,
    model_registry,
    recommended_for,
)
from sibyl_core.ai.validation import (
    KeyValidationResult,
    ModelValidationResult,
    SurfaceTestResult,
    check_model_availability,
    check_provider_key,
    test_surface_config,
)

__all__ = [
    "AIError",
    "ConfigField",
    "EnvConfigSource",
    "Extractor",
    "Generator",
    "KeyValidationResult",
    "LLMConfig",
    "LLMConfigError",
    "LLMConfigSource",
    "LLMError",
    "LLMProviderError",
    "LLMRateLimitError",
    "LLMSurface",
    "LLMTimeoutError",
    "LLMValidationError",
    "ModelCapability",
    "ModelEntry",
    "ModelKind",
    "ModelRegistry",
    "ModelValidationResult",
    "ResolvedLLMConfig",
    "SurfaceTestResult",
    "build_model",
    "check_model_availability",
    "check_provider_key",
    "classify_llm_exception",
    "embedding_entries",
    "get_config_source",
    "invalidate_llm_config",
    "llm_entries",
    "model_registry",
    "recommended_for",
    "resolve_llm_config",
    "resolve_provider_model_id",
    "set_config_source",
    "test_surface_config",
]
