"""Persistence adapters for the active relational and graph runtimes."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from sibyl.persistence.legacy.auth import (
        InvalidAuthClaimsError,
        LegacyAuthContextResolver,
        LegacyOrganizationMembershipRepository,
        LegacyOrganizationRepository,
        LegacySessionRepository,
        LegacyUserRepository,
        UserNotFoundError,
    )
    from sibyl.persistence.legacy.graph import (
        ActiveGraphStore,
        GraphQueryAdapter,
        GraphReadServiceAdapter,
        GraphWriteServiceAdapter,
        LegacyEntityStore,
        LegacyGraphQueryAdapter,
        LegacyGraphStore,
        LegacyKnowledgeReadAdapter,
        LegacyKnowledgeWriteAdapter,
        LegacyRelationshipStore,
        LegacySearchIndex,
        LegacyTaskRuntime,
        TaskGraphRuntime,
        ensure_graph_indexes,
        ensure_legacy_graph_indexes,
        execute_debug_query,
        execute_legacy_debug_query,
        get_entity_graph_runtime,
        get_graph_query_adapter,
        get_graph_stats_payload,
        get_knowledge_read_adapter,
        get_legacy_graph_stats_payload,
        get_legacy_knowledge_read_adapter,
        get_task_graph_runtime,
        graph_stats_payload,
        reset_graph_runtime,
        reset_legacy_graph_runtime,
    )

__all__ = [
    "ActiveGraphStore",
    "GraphQueryAdapter",
    "GraphReadServiceAdapter",
    "GraphWriteServiceAdapter",
    "InvalidAuthClaimsError",
    "LegacyAuthContextResolver",
    "LegacyOrganizationMembershipRepository",
    "LegacyOrganizationRepository",
    "LegacySessionRepository",
    "LegacyUserRepository",
    "LegacyEntityStore",
    "LegacyGraphQueryAdapter",
    "LegacyGraphStore",
    "LegacyKnowledgeReadAdapter",
    "LegacyKnowledgeWriteAdapter",
    "LegacyTaskRuntime",
    "LegacyRelationshipStore",
    "LegacySearchIndex",
    "TaskGraphRuntime",
    "ensure_graph_indexes",
    "ensure_legacy_graph_indexes",
    "execute_debug_query",
    "execute_legacy_debug_query",
    "get_entity_graph_runtime",
    "get_graph_query_adapter",
    "get_graph_stats_payload",
    "get_knowledge_read_adapter",
    "get_task_graph_runtime",
    "get_legacy_graph_stats_payload",
    "get_legacy_knowledge_read_adapter",
    "graph_stats_payload",
    "reset_graph_runtime",
    "reset_legacy_graph_runtime",
    "UserNotFoundError",
]


def __getattr__(name: str) -> Any:
    if name in set(__all__):
        from sibyl.persistence.legacy.auth import (
            InvalidAuthClaimsError,
            LegacyAuthContextResolver,
            LegacyOrganizationMembershipRepository,
            LegacyOrganizationRepository,
            LegacySessionRepository,
            LegacyUserRepository,
            UserNotFoundError,
        )

        exports = {
            "InvalidAuthClaimsError": InvalidAuthClaimsError,
            "LegacyAuthContextResolver": LegacyAuthContextResolver,
            "LegacyOrganizationMembershipRepository": LegacyOrganizationMembershipRepository,
            "LegacyOrganizationRepository": LegacyOrganizationRepository,
            "LegacySessionRepository": LegacySessionRepository,
            "LegacyUserRepository": LegacyUserRepository,
            "UserNotFoundError": UserNotFoundError,
        }
        if name in {
            "ActiveGraphStore",
            "GraphQueryAdapter",
            "GraphReadServiceAdapter",
            "GraphWriteServiceAdapter",
            "TaskGraphRuntime",
            "ensure_graph_indexes",
            "ensure_legacy_graph_indexes",
            "execute_debug_query",
            "execute_legacy_debug_query",
            "get_entity_graph_runtime",
            "get_graph_query_adapter",
            "get_graph_stats_payload",
            "get_knowledge_read_adapter",
            "get_task_graph_runtime",
            "LegacyEntityStore",
            "LegacyGraphQueryAdapter",
            "LegacyGraphStore",
            "LegacyKnowledgeReadAdapter",
            "LegacyKnowledgeWriteAdapter",
            "LegacyTaskRuntime",
            "LegacyRelationshipStore",
            "LegacySearchIndex",
            "get_legacy_graph_stats_payload",
            "get_legacy_knowledge_read_adapter",
            "graph_stats_payload",
            "reset_graph_runtime",
            "reset_legacy_graph_runtime",
        }:
            from sibyl.persistence.legacy.graph import (
                ActiveGraphStore,
                GraphQueryAdapter,
                GraphReadServiceAdapter,
                GraphWriteServiceAdapter,
                LegacyEntityStore,
                LegacyGraphQueryAdapter,
                LegacyGraphStore,
                LegacyKnowledgeReadAdapter,
                LegacyKnowledgeWriteAdapter,
                LegacyRelationshipStore,
                LegacySearchIndex,
                LegacyTaskRuntime,
                TaskGraphRuntime,
                ensure_graph_indexes,
                ensure_legacy_graph_indexes,
                execute_debug_query,
                execute_legacy_debug_query,
                get_entity_graph_runtime,
                get_graph_query_adapter,
                get_graph_stats_payload,
                get_knowledge_read_adapter,
                get_legacy_graph_stats_payload,
                get_legacy_knowledge_read_adapter,
                get_task_graph_runtime,
                graph_stats_payload,
                reset_graph_runtime,
                reset_legacy_graph_runtime,
            )

            exports.update(
                {
                    "ActiveGraphStore": ActiveGraphStore,
                    "GraphQueryAdapter": GraphQueryAdapter,
                    "GraphReadServiceAdapter": GraphReadServiceAdapter,
                    "GraphWriteServiceAdapter": GraphWriteServiceAdapter,
                    "TaskGraphRuntime": TaskGraphRuntime,
                    "ensure_graph_indexes": ensure_graph_indexes,
                    "ensure_legacy_graph_indexes": ensure_legacy_graph_indexes,
                    "execute_debug_query": execute_debug_query,
                    "execute_legacy_debug_query": execute_legacy_debug_query,
                    "get_entity_graph_runtime": get_entity_graph_runtime,
                    "get_graph_query_adapter": get_graph_query_adapter,
                    "get_graph_stats_payload": get_graph_stats_payload,
                    "get_knowledge_read_adapter": get_knowledge_read_adapter,
                    "get_task_graph_runtime": get_task_graph_runtime,
                    "LegacyEntityStore": LegacyEntityStore,
                    "LegacyGraphQueryAdapter": LegacyGraphQueryAdapter,
                    "LegacyGraphStore": LegacyGraphStore,
                    "LegacyKnowledgeReadAdapter": LegacyKnowledgeReadAdapter,
                    "LegacyKnowledgeWriteAdapter": LegacyKnowledgeWriteAdapter,
                    "LegacyTaskRuntime": LegacyTaskRuntime,
                    "LegacyRelationshipStore": LegacyRelationshipStore,
                    "LegacySearchIndex": LegacySearchIndex,
                    "get_legacy_graph_stats_payload": get_legacy_graph_stats_payload,
                    "get_legacy_knowledge_read_adapter": get_legacy_knowledge_read_adapter,
                    "graph_stats_payload": graph_stats_payload,
                    "reset_graph_runtime": reset_graph_runtime,
                    "reset_legacy_graph_runtime": reset_legacy_graph_runtime,
                }
            )
        return exports[name]
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)
