"""Active graph runtime adapters for API and persistence seams."""

from sibyl.persistence.legacy.graph import (
    ActiveGraphStore,
    GraphQueryAdapter,
    GraphReadServiceAdapter,
    GraphWriteServiceAdapter,
    TaskGraphRuntime,
    ensure_graph_indexes,
    ensure_legacy_graph_indexes,
    execute_debug_query,
    execute_legacy_debug_query,
    get_entity_graph_runtime,
    get_graph_query_adapter,
    get_graph_stats_payload,
    get_knowledge_read_adapter,
    get_legacy_graph_stats_payload,
    get_legacy_knowledge_read_adapter,
    get_task_graph_runtime,
    graph_stats_payload,
    reset_graph_runtime,
    reset_legacy_graph_runtime,
    update_legacy_entity as update_graph_entity,
)

__all__ = [
    "ActiveGraphStore",
    "GraphQueryAdapter",
    "GraphReadServiceAdapter",
    "GraphWriteServiceAdapter",
    "TaskGraphRuntime",
    "ensure_graph_indexes",
    "ensure_legacy_graph_indexes",
    "execute_debug_query",
    "execute_legacy_debug_query",
    "get_entity_graph_runtime",
    "get_graph_query_adapter",
    "get_graph_stats_payload",
    "get_knowledge_read_adapter",
    "get_legacy_graph_stats_payload",
    "get_legacy_knowledge_read_adapter",
    "get_task_graph_runtime",
    "graph_stats_payload",
    "reset_graph_runtime",
    "reset_legacy_graph_runtime",
    "update_graph_entity",
]
